#! /usr/bin/env ruby

require 'pg'

CONNECTION = PG.connect(dbname: 'expenses')

def list_help
  puts <<-HELP
An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field
  HELP
end

def list_expenses
  all_expenses = CONNECTION.exec 'SELECT * FROM expenses'

  all_expenses.each do |tuple|
    columns = [ tuple['id'].rjust(3),
                tuple['created_on'].rjust(10),
                tuple['amount'].rjust(12),
                tuple['memo'] ]
    puts columns.join(' | ')
  end
end

def add_expense
  amount = ARGV[1]
  memo = ARGV[2]

  if (amount.nil? || memo.nil?)
    puts 'AMOUNT and MEMO must be provided'
    return
  end

  today = Date.today
  CONNECTION.exec "INSERT INTO expenses (amount, memo, created_on) VALUES (#{amount}, '#{memo}', '#{today}')"
end

case ARGV.first
when 'list'
  list_expenses
when 'add'
  add_expense
else
  list_help
end
